receivers:
  syslog:
    tcp:
      listen_address: "0.0.0.0:54526"
    protocol: rfc5424

# Thanks Claude Haiku 4.5 for the log parsing logic!
# TODO: Look at the router connector:
# https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/connector/routingconnector/README.md
# It may help us understand what to do.
processors:
  transform/get_operation:
    log_statements:
      - context: log
        statements:
          # Split message to the fields and save them.
          - set(log.attributes["fields"], Split(log.attributes["message"], "|"))
          # Set the operation it needs to do.
          # For file operations it's at the 6th index.
          # For other operations it will be the `ntStatus`.
          - set(log.attributes["operation"], log.attributes["fields"][6])
          # The user SID is always at the 0th index,
          # so we can set it as an attribute for all logs.
          - set(log.attributes["user_sid"], log.attributes["fields"][0])

exporters:
  file:
    path: /mnt/logs/logs.jsonl

extensions:
  health_check:
    endpoint: 0.0.0.0:13133

service:
  extensions: [health_check]
  pipelines:
    logs:
      receivers: [syslog]
      processors: [transform/get_operation]
      exporters: [file]
